-- =============================================================
-- RAGfier consolidated head schema snapshot.
--
-- This file is a rendered snapshot of the current database schema
-- after all migrations under sql/migrations/ have been applied.
-- It is intended for reference, onboarding, and diff review only.
--
-- DO NOT edit this file by hand to evolve the schema. The source of
-- truth for schema changes is sql/migrations/ (sequential dbmate
-- up/down files). To regenerate this file after adding a migration,
-- run `./scripts/dump-schema.sh`.
--
-- Ordering: extensions → Phase 1 → Phase 2 → Phase 3 → Phase 4.
-- =============================================================

-- =============================================================
-- Extensions
-- =============================================================
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================
-- Phase 1: Core ingestion + retrieval
-- =============================================================

-- ---- Tables ----

CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  plan TEXT DEFAULT 'free',
  settings JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ingestion_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
    -- Valid statuses: pending | parsing | chunking | embedding | completed | failed
  total_chunks INTEGER DEFAULT 0,
  processed_chunks INTEGER DEFAULT 0,
  error_message TEXT,
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  -- Added in Phase 4
  knowledge_base_id UUID,
  source_id UUID,
  source_type TEXT
);

CREATE TABLE IF NOT EXISTS documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  job_id UUID REFERENCES ingestion_jobs(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  embedding VECTOR(1536),
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  -- Added in Phase 2
  fts tsvector GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,
  -- Added in Phase 4
  knowledge_base_id UUID,
  source_type TEXT,
  source_id UUID,
  status TEXT NOT NULL DEFAULT 'active'
);

-- ---- Indexes ----

CREATE INDEX IF NOT EXISTS idx_documents_embedding
  ON documents
  USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_documents_tenant_id
  ON documents (tenant_id);

CREATE INDEX IF NOT EXISTS idx_documents_job_id
  ON documents (job_id);

CREATE INDEX IF NOT EXISTS idx_documents_metadata
  ON documents
  USING gin (metadata);

CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_tenant_status
  ON ingestion_jobs (tenant_id, status);

-- ---- RLS ----

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingestion_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tenant_isolation_select" ON documents;
CREATE POLICY "tenant_isolation_select" ON documents
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "service_role_insert" ON documents;
CREATE POLICY "service_role_insert" ON documents
  FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "tenant_isolation_jobs" ON ingestion_jobs;
CREATE POLICY "tenant_isolation_jobs" ON ingestion_jobs
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

-- =============================================================
-- Phase 2: Hybrid retrieval + prompt versioning
-- =============================================================

-- ---- Indexes ----

CREATE INDEX IF NOT EXISTS idx_documents_fts
  ON documents
  USING gin (fts);

-- ---- Tables ----

CREATE TABLE IF NOT EXISTS prompt_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  system_prompt TEXT NOT NULL,
  user_prompt_template TEXT NOT NULL,
  metadata JSONB DEFAULT '{}'::JSONB,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_prompt_active
  ON prompt_versions (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::UUID), name)
  WHERE is_active = true;

-- ---- RLS ----

ALTER TABLE prompt_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tenant_isolation_prompts" ON prompt_versions;
CREATE POLICY "tenant_isolation_prompts" ON prompt_versions
  FOR SELECT
  USING (
    tenant_id IS NULL
    OR tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

-- =============================================================
-- Phase 3: Evaluation pipeline
-- =============================================================

-- ---- Tables ----

CREATE TABLE IF NOT EXISTS eval_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  dataset_version TEXT NOT NULL,
  trigger TEXT NOT NULL,
  git_sha TEXT,
  git_branch TEXT,
  status TEXT NOT NULL DEFAULT 'running',
  faithfulness_avg DOUBLE PRECISION,
  answer_relevancy_avg DOUBLE PRECISION,
  context_precision_avg DOUBLE PRECISION,
  context_recall_avg DOUBLE PRECISION,
  citation_coverage_avg DOUBLE PRECISION,
  decline_accuracy_avg DOUBLE PRECISION,
  latency_compliance_avg DOUBLE PRECISION,
  thresholds JSONB NOT NULL DEFAULT '{}'::JSONB,
  passed BOOLEAN,
  failure_reasons JSONB DEFAULT '[]'::JSONB,
  total_samples INTEGER DEFAULT 0,
  failed_samples INTEGER DEFAULT 0,
  eval_model TEXT,
  total_eval_cost_usd DOUBLE PRECISION,
  duration_seconds DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS eval_sample_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  eval_run_id UUID NOT NULL REFERENCES eval_runs(id) ON DELETE CASCADE,
  sample_id TEXT NOT NULL,
  category TEXT,
  user_input TEXT NOT NULL,
  response TEXT NOT NULL,
  retrieved_contexts JSONB NOT NULL DEFAULT '[]'::JSONB,
  reference TEXT,
  faithfulness DOUBLE PRECISION,
  answer_relevancy DOUBLE PRECISION,
  context_precision DOUBLE PRECISION,
  context_recall DOUBLE PRECISION,
  citation_coverage DOUBLE PRECISION,
  decline_accuracy DOUBLE PRECISION,
  latency_ms DOUBLE PRECISION,
  passed BOOLEAN,
  failure_reasons JSONB DEFAULT '[]'::JSONB,
  num_chunks_retrieved INTEGER,
  top_rerank_score DOUBLE PRECISION,
  model_used TEXT,
  prompt_version TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ---- Indexes ----

CREATE INDEX IF NOT EXISTS idx_eval_runs_tenant
  ON eval_runs (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_eval_runs_git
  ON eval_runs (git_sha);

CREATE INDEX IF NOT EXISTS idx_eval_sample_results_run
  ON eval_sample_results (eval_run_id);

CREATE INDEX IF NOT EXISTS idx_eval_sample_results_category
  ON eval_sample_results (eval_run_id, category);

-- ---- RLS ----

ALTER TABLE eval_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE eval_sample_results ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tenant_isolation_eval_runs" ON eval_runs;
CREATE POLICY "tenant_isolation_eval_runs" ON eval_runs
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "tenant_isolation_eval_samples" ON eval_sample_results;
CREATE POLICY "tenant_isolation_eval_samples" ON eval_sample_results
  FOR SELECT
  USING (
    eval_run_id IN (
      SELECT id FROM eval_runs
      WHERE tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
    )
  );

-- =============================================================
-- Phase 4: Hosted platform (tenancy, keys, connectors, observability)
-- =============================================================

-- ---- Tables ----

CREATE TABLE IF NOT EXISTS knowledge_bases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  settings JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (tenant_id, slug)
);

CREATE TABLE IF NOT EXISTS integrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  environment TEXT NOT NULL DEFAULT 'production',
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS api_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  integration_id UUID NOT NULL REFERENCES integrations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  prefix TEXT NOT NULL UNIQUE,
  secret_hash TEXT NOT NULL,
  scopes JSONB NOT NULL DEFAULT '[]'::JSONB,
  status TEXT NOT NULL DEFAULT 'active',
  expires_at TIMESTAMPTZ,
  last_used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS connector_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  knowledge_base_id UUID NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  sync_mode TEXT NOT NULL DEFAULT 'manual',
  encrypted_config TEXT NOT NULL,
  config_summary JSONB NOT NULL DEFAULT '{}'::JSONB,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS connector_sync_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  connector_source_id UUID NOT NULL REFERENCES connector_sources(id) ON DELETE CASCADE,
  knowledge_base_id UUID NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  trigger TEXT NOT NULL DEFAULT 'manual',
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  error_message TEXT,
  started_at TIMESTAMPTZ DEFAULT now(),
  finished_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  actor_type TEXT NOT NULL,
  actor_id TEXT,
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS request_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  integration_id UUID REFERENCES integrations(id) ON DELETE SET NULL,
  api_key_id UUID REFERENCES api_keys(id) ON DELETE SET NULL,
  actor_type TEXT NOT NULL DEFAULT 'api_key',
  endpoint TEXT NOT NULL,
  method TEXT NOT NULL,
  status_code INTEGER NOT NULL,
  latency_ms INTEGER NOT NULL DEFAULT 0,
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  error_code TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS usage_rollups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  integration_id UUID REFERENCES integrations(id) ON DELETE SET NULL,
  bucket_start TIMESTAMPTZ NOT NULL,
  granularity TEXT NOT NULL DEFAULT 'day',
  request_count INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  total_input_tokens INTEGER NOT NULL DEFAULT 0,
  total_output_tokens INTEGER NOT NULL DEFAULT 0,
  avg_latency_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (tenant_id, integration_id, bucket_start, granularity)
);

-- ---- Cross-table FK wiring (inline with Phase 1 tables after Phase 4 alters) ----
-- documents.knowledge_base_id -> knowledge_bases(id) ON DELETE SET NULL
-- ingestion_jobs.knowledge_base_id -> knowledge_bases(id) ON DELETE SET NULL
-- These are applied via ALTER TABLE in sql/migrations/202604160004_phase4_hosted_platform.sql.
-- The reference form below documents the resulting constraints.

ALTER TABLE documents
  DROP CONSTRAINT IF EXISTS documents_knowledge_base_id_fkey,
  ADD CONSTRAINT documents_knowledge_base_id_fkey
    FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id) ON DELETE SET NULL;

ALTER TABLE ingestion_jobs
  DROP CONSTRAINT IF EXISTS ingestion_jobs_knowledge_base_id_fkey,
  ADD CONSTRAINT ingestion_jobs_knowledge_base_id_fkey
    FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id) ON DELETE SET NULL;

-- ---- Indexes ----

CREATE INDEX IF NOT EXISTS idx_knowledge_bases_tenant
  ON knowledge_bases (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_integrations_tenant
  ON integrations (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_api_keys_integration
  ON api_keys (tenant_id, integration_id, status);

CREATE INDEX IF NOT EXISTS idx_documents_kb
  ON documents (tenant_id, knowledge_base_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_jobs_kb
  ON ingestion_jobs (tenant_id, knowledge_base_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_connector_sources_tenant
  ON connector_sources (tenant_id, knowledge_base_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_connector_sync_jobs_connector
  ON connector_sync_jobs (tenant_id, connector_source_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_request_logs_tenant
  ON request_logs (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant
  ON audit_logs (tenant_id, created_at DESC);

-- ---- RLS ----

ALTER TABLE knowledge_bases ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE connector_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE connector_sync_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE request_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_rollups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tenant_isolation_knowledge_bases" ON knowledge_bases;
CREATE POLICY "tenant_isolation_knowledge_bases" ON knowledge_bases
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "tenant_isolation_integrations" ON integrations;
CREATE POLICY "tenant_isolation_integrations" ON integrations
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "tenant_isolation_api_keys" ON api_keys;
CREATE POLICY "tenant_isolation_api_keys" ON api_keys
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "tenant_isolation_connector_sources" ON connector_sources;
CREATE POLICY "tenant_isolation_connector_sources" ON connector_sources
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "tenant_isolation_connector_sync_jobs" ON connector_sync_jobs;
CREATE POLICY "tenant_isolation_connector_sync_jobs" ON connector_sync_jobs
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "tenant_isolation_audit_logs" ON audit_logs;
CREATE POLICY "tenant_isolation_audit_logs" ON audit_logs
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "tenant_isolation_request_logs" ON request_logs;
CREATE POLICY "tenant_isolation_request_logs" ON request_logs
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

DROP POLICY IF EXISTS "tenant_isolation_usage_rollups" ON usage_rollups;
CREATE POLICY "tenant_isolation_usage_rollups" ON usage_rollups
  FOR SELECT
  USING (
    tenant_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::UUID
  );

-- =============================================================
-- RPC functions (current/head versions)
-- =============================================================
--
-- NOTE: Phase 1 and Phase 2 introduced narrower-signature variants of
-- match_documents and match_documents_hybrid. Phase 4 adds new
-- overloads with an extra filter_knowledge_base_ids UUID[] parameter;
-- because the signatures differ, PostgreSQL treats them as distinct
-- functions and both coexist in the live database. The head overloads
-- (Phase 4) are the ones the application calls — earlier overloads are
-- left in place for backward compatibility.

-- ---- match_documents (Phase 1 signature, kept for compatibility) ----
CREATE OR REPLACE FUNCTION match_documents(
  query_embedding VECTOR(1536),
  match_count INT DEFAULT 5,
  filter_tenant_id UUID DEFAULT NULL
)
RETURNS TABLE (
  id UUID,
  content TEXT,
  metadata JSONB,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) AS similarity
  FROM documents d
  WHERE
    (filter_tenant_id IS NULL OR d.tenant_id = filter_tenant_id)
  ORDER BY d.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ---- match_documents (Phase 4 head signature) ----
CREATE OR REPLACE FUNCTION match_documents(
  query_embedding VECTOR(1536),
  match_count INT DEFAULT 5,
  filter_tenant_id UUID DEFAULT NULL,
  filter_knowledge_base_ids UUID[] DEFAULT NULL
)
RETURNS TABLE (
  id UUID,
  content TEXT,
  metadata JSONB,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) AS similarity
  FROM documents d
  WHERE
    (filter_tenant_id IS NULL OR d.tenant_id = filter_tenant_id)
    AND (
      filter_knowledge_base_ids IS NULL
      OR d.knowledge_base_id = ANY(filter_knowledge_base_ids)
    )
  ORDER BY d.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ---- match_documents_hybrid (Phase 2 signature, kept for compatibility) ----
CREATE OR REPLACE FUNCTION match_documents_hybrid(
  query_embedding VECTOR(1536),
  query_text TEXT,
  match_count INT DEFAULT 20,
  rrf_k INT DEFAULT 60,
  dense_top_n INT DEFAULT 20,
  sparse_top_n INT DEFAULT 20,
  filter_tenant_id UUID DEFAULT NULL
)
RETURNS TABLE (
  id UUID,
  content TEXT,
  metadata JSONB,
  rrf_score FLOAT,
  dense_rank INT,
  sparse_rank INT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  WITH dense AS (
    SELECT
      d.id,
      d.content,
      d.metadata,
      ROW_NUMBER() OVER (ORDER BY d.embedding <=> query_embedding)::INT AS rank
    FROM documents d
    WHERE (filter_tenant_id IS NULL OR d.tenant_id = filter_tenant_id)
    ORDER BY d.embedding <=> query_embedding
    LIMIT dense_top_n
  ),
  sparse AS (
    SELECT
      d.id,
      d.content,
      d.metadata,
      ROW_NUMBER() OVER (
        ORDER BY ts_rank(d.fts, websearch_to_tsquery('english', query_text)) DESC
      )::INT AS rank
    FROM documents d
    WHERE
      (filter_tenant_id IS NULL OR d.tenant_id = filter_tenant_id)
      AND d.fts @@ websearch_to_tsquery('english', query_text)
    ORDER BY ts_rank(d.fts, websearch_to_tsquery('english', query_text)) DESC
    LIMIT sparse_top_n
  ),
  fused AS (
    SELECT
      COALESCE(dense.id, sparse.id) AS id,
      COALESCE(dense.content, sparse.content) AS content,
      COALESCE(dense.metadata, sparse.metadata) AS metadata,
      (COALESCE(1.0::double precision / (rrf_k + dense.rank), 0)
        + COALESCE(1.0::double precision / (rrf_k + sparse.rank), 0))::double precision AS rrf_score,
      dense.rank AS dense_rank,
      sparse.rank AS sparse_rank
    FROM dense
    FULL OUTER JOIN sparse ON dense.id = sparse.id
  )
  SELECT
    fused.id,
    fused.content,
    fused.metadata,
    fused.rrf_score,
    COALESCE(fused.dense_rank, 0),
    COALESCE(fused.sparse_rank, 0)
  FROM fused
  ORDER BY fused.rrf_score DESC
  LIMIT match_count;
END;
$$;

-- ---- match_documents_hybrid (Phase 4 head signature) ----
CREATE OR REPLACE FUNCTION match_documents_hybrid(
  query_embedding VECTOR(1536),
  query_text TEXT,
  match_count INT DEFAULT 20,
  rrf_k INT DEFAULT 60,
  dense_top_n INT DEFAULT 20,
  sparse_top_n INT DEFAULT 20,
  filter_tenant_id UUID DEFAULT NULL,
  filter_knowledge_base_ids UUID[] DEFAULT NULL
)
RETURNS TABLE (
  id UUID,
  content TEXT,
  metadata JSONB,
  rrf_score FLOAT,
  dense_rank INT,
  sparse_rank INT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  WITH dense AS (
    SELECT
      d.id,
      d.content,
      d.metadata,
      ROW_NUMBER() OVER (ORDER BY d.embedding <=> query_embedding)::INT AS rank
    FROM documents d
    WHERE
      (filter_tenant_id IS NULL OR d.tenant_id = filter_tenant_id)
      AND (
        filter_knowledge_base_ids IS NULL
        OR d.knowledge_base_id = ANY(filter_knowledge_base_ids)
      )
    ORDER BY d.embedding <=> query_embedding
    LIMIT dense_top_n
  ),
  sparse AS (
    SELECT
      d.id,
      d.content,
      d.metadata,
      ROW_NUMBER() OVER (
        ORDER BY ts_rank(d.fts, websearch_to_tsquery('english', query_text)) DESC
      )::INT AS rank
    FROM documents d
    WHERE
      (filter_tenant_id IS NULL OR d.tenant_id = filter_tenant_id)
      AND (
        filter_knowledge_base_ids IS NULL
        OR d.knowledge_base_id = ANY(filter_knowledge_base_ids)
      )
      AND d.fts @@ websearch_to_tsquery('english', query_text)
    ORDER BY ts_rank(d.fts, websearch_to_tsquery('english', query_text)) DESC
    LIMIT sparse_top_n
  ),
  fused AS (
    SELECT
      COALESCE(dense.id, sparse.id) AS id,
      COALESCE(dense.content, sparse.content) AS content,
      COALESCE(dense.metadata, sparse.metadata) AS metadata,
      (COALESCE(1.0::double precision / (rrf_k + dense.rank), 0)
        + COALESCE(1.0::double precision / (rrf_k + sparse.rank), 0))::double precision AS rrf_score,
      dense.rank AS dense_rank,
      sparse.rank AS sparse_rank
    FROM dense
    FULL OUTER JOIN sparse ON dense.id = sparse.id
  )
  SELECT
    fused.id,
    fused.content,
    fused.metadata,
    fused.rrf_score,
    COALESCE(fused.dense_rank, 0),
    COALESCE(fused.sparse_rank, 0)
  FROM fused
  ORDER BY fused.rrf_score DESC
  LIMIT match_count;
END;
$$;
